export const string = {
    login: 'Login',
    register: 'Register',
    userName: 'Username',
    email: 'Email',
    password: 'Password',
    findHomemate: 'Find Home-mate',
    diary: 'Diary',
    find: 'Find',
    plan: 'Plan',
    diaryPlaceholder: 'Dear diary, ...',
    createNewDiary: 'Add',
    hope: 'Hope',
    you: 'You',
    happy: 'Happy',
    currentProvince: 'Current province',
    currentTown: 'Current town',
    homeProvince: 'Home province',
    homeTown: 'Home town',
    goodMorning: 'Good morning,',
    goodNoon: 'Good noon,',
    goodAfternoon: 'Good afternoon,',
    goodEvening: 'Good evening,',
    goodNight: 'Good night,',
    addMyInfomation: 'Add my information',
    fullFill: 'Let fill full information',
    createNewPlan: 'New plan',
    addAction: 'Action',
    with: 'with',
    profile: 'profile',
    contact: 'contact',
    recommend: 'Recommend',
    planPlace: 'At',
    at: 'At',
    chooseFavoriteColor: 'Choose your favorite color',
    close: 'Close',
    darkMode: 'Dark mode',
    diaryDescription: 'How is your day?',
    planDescription: 'Do it!',
    yourThings: 'Your things',
    noPlanYet: 'No plan yet',
    done: 'Done',
    placeHolder: 'What you gonna do with who'
}